sudo: enabled
language: python
python:
  - 3.6

notifications:
  slack: "cryptobotgroupe:vYDDCLRne52jPGVtN6cMiUkb"
  email: false
install:
  - git clone https://github.com/Drakkar-Software/OctoBot.git
  - cd OctoBot
  - git checkout dev
  - sudo bash ./docs/install/linux_dependencies.sh
  - pip3 install -r pre_requirements.txt
  - pip3 install -r requirements.txt
  - cp ../octobot_config.json ./config.json
  - python3 start.py -p install all
script:
  - pip3 install -r dev_requirements.txt
  - pytest --cov=. --cov-config=.coveragerc ./tentacles/tests/


